add catch exception in checking steps

diff --git a/.github/workflows/provision_efs_csi_driver_3.yaml b/.github/workflows/provision_efs_csi_driver_3.yaml
--- a/.github/workflows/provision_efs_csi_driver_3.yaml
+++ b/.github/workflows/provision_efs_csi_driver_3.yaml
@@ -127,15 +127,25 @@ jobs:
       - name: Check if IAM policy and role exists
         id: check-iamserviceaccount
         run: |
-          output=$(kubectl get serviceaccount efs-csi-controller-sa -n kube-system -o custom-columns=:metadata.name)
-
-          if [[ -z "$output" ]]; then
-            echo "IAM Service Account does not exist."
-            echo "::set-output name=role_exists::false"
-          else
-            echo "IAM Service Account exists."
-            echo "::set-output name=role_exists::true"
-          fi
+          try {
+            output=$(kubectl get serviceaccount efs-csi-controller-sa -n kube-system -o custom-columns=:metadata.name)
+          
+            if [[ -z "$output" ]]; then
+              echo "IAM Service Account does not exist."
+              echo "::set-output name=role_exists::false"
+            else
+              echo "IAM Service Account exists."
+              echo "::set-output name=role_exists::true"
+            fi
+          } catch {
+            if echo "$output" | grep -q "Error from server (NotFound): serviceaccounts \"efs-csi-controller-sa\" not found"; then
+              echo "The specified service account was not found."
+              echo "::set-output name=role_exists::false"
+            else
+              echo "An error occurred: $output"
+              exit 1
+            fi
+          }
 
       - name: Create an IAM policy and role
         id: create-iam-role
